namespace: everpure
name: flashblade
version: 1.28.0
readme: README.md
authors:
  - Everpure Ansible Team <pure-ansible-team@everpuredata.com>
description: Collection of modules to manage Everpure FlashBlade
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
tags:
  - everpure
  - purestorage
  - flashblade
  - storage
  - object
  - nfs
dependencies: {}
repository: https://github.com/Everpure-Ansible/FlashBlade-Collection
documentation: https://docs.ansible.com/ansible/latest/collections/everpure/flashblade/index.html#plugins-in-everpure-flashblade
issues: https://github.com/Everpure-Ansible/FlashBlade-Collection/issues
